"""
Django settings for remispoint project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$(e-ht#j!c@u92g*6!9%%f6_u$3t1f&+1*)l))4fd&)m710%u-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'remis_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'remispoint.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['remis_app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'remispoint.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'remispoint_new',  # Nombre de la base de datos
        'USER': 'postgres',    # Usuario de la base de datos
        'PASSWORD': 'loko123', # Contraseña del usuario
        'HOST': 'localhost',   # Host (puede ser una IP o "localhost")
        'PORT': '5432',        # Puerto de conexión
        'OPTIONS': {
            'options': '-c client_encoding=UTF8',  # Especifica que use UTF-8
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

ORS_API_KEY = "5b3ce3597851110001cf6248bbaa88fc959c42db9efc751597c03a47"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    "https://comic-presumably-dogfish.ngrok-free.app"
]


MP_PUBLIC_KEY = os.getenv('MP_PUBLIC_KEY', 'APP_USR-6230e0e3-2ba6-478f-9814-2630b421b3d8')
MP_CLIENT_ID = os.getenv('MP_CLIENT_ID', '889360435513211')
MP_CLIENT_SECRET = os.getenv('MP_CLIENT_SECRET', 'fxqbU1OXJPpsTPnZHRvbaVRU2taehfKC')
MP_ACCESS_TOKEN = os.getenv('MP_ACESS_TOKEN', 'APP_USR-889360435513211-021517-b0e41944ffc500bf962b5045441c2ad2-131987175')
MP_REDIRECT_URI = os.getenv('MP_REDIRECT_URI', 'https://comic-presumably-dogfish.ngrok-free.app/mercadopago/callback/')
SITE_URL = os.getenv('SITE_URL', 'https://comic-presumably-dogfish.ngrok-free.app')

# Configuración del timezone en Argentina
TIME_ZONE = "America/Argentina/Buenos_Aires"

# Mantener la configuración de uso de timezone en True
USE_TZ = False
