# Generated by Django 5.1.4 on 2024-12-07 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Localidad',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('tipo_cuenta', models.IntegerField()),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remis_app.localidad')),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='PedidosCliente',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('dir_salida', models.CharField(max_length=255)),
                ('dir_destino', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
