# Generated by Django 5.1.4 on 2024-12-27 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remis_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('patente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('anio_modelo', models.IntegerField()),
                ('propietario', models.CharField(max_length=100)),
                ('vtv', models.DateField()),
                ('venc_patente', models.DateField()),
                ('id_remiseria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Autos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nro_tel', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Chofer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChoferAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField()),
            ],
            options={
                'db_table': 'ChoferAuto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('dir_salida', models.CharField(max_length=255)),
                ('dir_destino', models.CharField(max_length=255)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('id_precio', models.IntegerField()),
                ('cod_tipo_pago', models.CharField(max_length=50)),
                ('id_remiseria', models.CharField(max_length=100)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Viajes',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedidoscliente',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
